### ISSUE TITLE
How to get latest version of of PowerPoint

### ISSUE THREAD

**Issue by mhasan64** [OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart#1]
I am trying to get this sample (Insert Excel charts using Microsoft Graph in a PowerPoint Add-in) working in PowerPoint. One of the requirement is that a specific version of PowerPoint "PowerPoint for Windows Desktop, version 16.0.6769.2001 or higher" is needed. I have Office 365 subscription (work related) and my PowerPoint version is "16.0.6001.1068". I have already checked in PowerPoint for any available update but it comes back saying my version is up to date.

The question is - how else can i get the "16.0.6769.2001" version? Any help would be appreciated.

BTW: i did go through all the other settings and instruction to setup the the sample. When i load PowerPoint and insert a chart, the add in never loads.

Cheers.

**Comment by Reezaali** [comment]
Hi @mhasan64, thanks for using the sample! Maybe this article can help you: [http://dev.office.com/docs/add-ins/develop/install-latest-office-version](http://dev.office.com/docs/add-ins/develop/install-latest-office-version)? After you've tried those steps, can you open a new issue if the add-in never loads please? Thanks!

**Comment by mhasan64** [comment]
Perfect. This did work. Thank you very much Reezaall for all your help.
