### ISSUE TITLE
Sideload a Powerpoint Add-in on the desktop

### ISSUE THREAD

**Issue by buaahsh** [OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart#4]
Hi, 

Can I test or debug a Powerpoint Add-in on the desktop, like [Outlook]?(https://dev.office.com/docs/add-ins/testing/sideload-outlook-add-ins-for-testing)

**Comment by Reezaali** [comment]
Sideloading in PowerPoint/Excel/Word is a little different. Here is a link to the steps to follow: [Sideload Office Add-ins for testing](https://dev.office.com/docs/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins). 

Note that you'll need to host your files on a web server. Running from Visual Studio makes this pretty easy. Here's a link to steps to follow for hosting in Azure: [Host an Office Add-in on Microsoft Azure](https://dev.office.com/docs/add-ins/publish/host-an-office-add-in-on-microsoft-azure)
Thanks!

**Comment by buaahsh** [comment]
Thanks for your response.

I found that JavaScript API of PowerPoint didn't support writing HTML to the selection. [Document.setSelectedDataAsync method](https://dev.office.com/reference/add-ins/shared/document.setselecteddataasync?product=powerpoint) 

I want to insert HTML in PowerPoint. What should I do?
