### ISSUE TITLE
missing mdf file

### ISSUE THREAD

**Issue by ashuetawah** [OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart#6]
In web.config, there is a AttachDbFilename=|DataDirectory|PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart.mdf param while in project there is no mdf file is available. Could you please add the missing file?

**Comment by Rick-Kirkham** [comment]
Is the sample not working for you?

**Comment by ashuetawah** [comment]
It worked after pointing to a different local db.

**Comment by Rick-Kirkham** [comment]
This is now fixed. I've added the DB files and fixed the gitignore so that it won't ignore them anymore.
